name: quickbites
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.0
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
