name: quickbites
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^4.15.0
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.5
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
  - lib/customer/pages/Dashboard/assets/tacobell.jpg
  - lib/customer/pages/Dashboard/assets/zaxbys.jpg
  - lib/customer/pages/Dashboard/assets/redlobster.jpg
  - lib/customer/pages/Dashboard/assets/wendys.jpg
  - lib/customer/pages/Dashboard/assets/popeyes.jpg
  - lib/customer/pages/Menu/assets/tacobell/beefy_five_layer.jpg
  - lib/customer/pages/Menu/assets/tacobell/cinnabon_delights.jpg
  - lib/customer/pages/Menu/assets/tacobell/crunchwrap_supreme.jpg
  - lib/customer/pages/Menu/assets/tacobell/crunchy_taco.jpg
  - lib/customer/pages/Menu/assets/tacobell/medium_drink.jpg
  - lib/customer/pages/Menu/assets/zaxbys/big_zax.jpg
  - lib/customer/pages/Menu/assets/zaxbys/funnel_cake.jpg
  - lib/customer/pages/Menu/assets/zaxbys/house_zalad.jpg
  - lib/customer/pages/Menu/assets/zaxbys/loaded_fries.jpg
  - lib/customer/pages/Menu/assets/zaxbys/philly.jpg
  - lib/customer/pages/Menu/assets/redlobster/biscuits.jpg
  - lib/customer/pages/Menu/assets/redlobster/brownie_overboard.jpg
  - lib/customer/pages/Menu/assets/redlobster/cajun_linguini.jpg
  - lib/customer/pages/Menu/assets/redlobster/ny_strip.jpg
  - lib/customer/pages/Menu/assets/redlobster/twin_maine.jpg
  - lib/customer/pages/Menu/assets/popeyes/friedchicken.jpg
  - lib/customer/pages/Menu/assets/popeyes/nuggets.jpg
  - lib/customer/pages/Menu/assets/popeyes/oreocheesecake.jpg
  - lib/customer/pages/Menu/assets/popeyes/popcornshrimp.jpg
  - lib/customer/pages/Menu/assets/popeyes/tenders.jpg
  - lib/customer/pages/Menu/assets/wendys/applepecansalad.jpg
  - lib/customer/pages/Menu/assets/wendys/baconator.jpg
  - lib/customer/pages/Menu/assets/wendys/ghostpeppersandwich.jpg
  - lib/customer/pages/Menu/assets/wendys/peppermintfrosty.jpg
  - lib/customer/pages/Menu/assets/wendys/spicynuggets.jpg
